packageExtensions:
  "@nestjs/apollo@*":
    dependencies:
      apollo-server-core: ^3.5.0
      graphql: ^15.3.0 || ^16.0.0
  apollo-server-core@*:
    dependencies:
      graphql: ^15.3.0 || ^16.0.0
  apollo-server-errors@*:
    dependencies:
      graphql: ^15.3.0 || ^16.0.0
  apollo-server-express@*:
    dependencies:
      express: ^4.17.1
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"
  "@aws-sdk/lib-dynamodb@*":
    dependencies:
      "@smithy/smithy-client": "*"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
