packageExtensions:
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": 11.9.0
      "@emotion/styled": 11.8.1
  "@nestjs/apollo@*":
    dependencies:
      apollo-server-core: ^3.5.0
      graphql: ^15.3.0 || ^16.0.0
  apollo-server-core@*:
    dependencies:
      graphql: ^15.3.0 || ^16.0.0
  apollo-server-errors@*:
    dependencies:
      graphql: ^15.3.0 || ^16.0.0
  apollo-server-express@*:
    dependencies:
      express: ^4.17.1
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
